# scipy.spatial Module Overview

The `scipy.spatial` module provides various functions for working with spatial data, including distance computations, spatial trees, and convex hulls.

## 1. Distance Functions

### Euclidean Distance
- **`scipy.spatial.distance.euclidean(u, v)`**: Computes the Euclidean distance between two points.

### Other Distance Metrics
- **`scipy.spatial.distance.cityblock(u, v)`**: Computes the Manhattan distance (L1 norm).
- **`scipy.spatial.distance.cosine(u, v)`**: Computes the cosine distance.
- **`scipy.spatial.distance.jaccard(u, v)`**: Computes the Jaccard distance.
- **`scipy.spatial.distance.sqeuclidean(u, v)`**: Computes the squared Euclidean distance.

In [2]:
import numpy as np
from scipy.spatial import distance

# Example 1: Euclidean Distance
# Euclidean distance is the straight-line distance between two points in Euclidean space.
u = np.array([1, 2])
v = np.array([4, 6])
euclidean_dist = distance.euclidean(u, v)
print("Euclidean Distance between u and v:", euclidean_dist)

# Example 2: Manhattan (Cityblock) Distance
# Manhattan distance (also known as L1 norm or Taxicab distance) is the sum of the absolute differences of their coordinates.
manhattan_dist = distance.cityblock(u, v)
print("Manhattan Distance between u and v:", manhattan_dist)

# Example 3: Cosine Distance
# Cosine distance is computed as 1 minus the cosine similarity between two vectors.
# It ranges from 0 (when vectors are identical) to 1 (when vectors are orthogonal).
cosine_dist = distance.cosine(u, v)
print("Cosine Distance between u and v:", cosine_dist)

# Example 4: Jaccard Distance
# Jaccard distance is used to compare the similarity and diversity of sample sets.
# It's defined as 1 minus the Jaccard index, where the Jaccard index is the size of the intersection divided by the size of the union of the sample sets.
# In this case, we convert u and v to sets for demonstration.
u_set = set([1, 2, 3])
v_set = set([3, 4, 5])
jaccard_dist = distance.jaccard(u, v)
print("Jaccard Distance between u_set and v_set:", jaccard_dist)

# Example 5: Squared Euclidean Distance
# Squared Euclidean distance is similar to the Euclidean distance, but without taking the square root.
sqeuclidean_dist = distance.sqeuclidean(u, v)
print("Squared Euclidean Distance between u and v:", sqeuclidean_dist)


Euclidean Distance between u and v: 5.0
Manhattan Distance between u and v: 7
Cosine Distance between u and v: 0.007722123286332261
Jaccard Distance between u_set and v_set: 1.0
Squared Euclidean Distance between u and v: 25.0


### Distance Matrix
- **`scipy.spatial.distance.pdist(X, metric='euclidean')`**: Computes the pairwise distances between observations in n-dimensional space.
- **`scipy.spatial.distance.squareform(x)`**: Converts a distance vector to a square distance matrix and vice versa.

In [3]:
import numpy as np
from scipy.spatial import distance

# Example: Pairwise Distance Matrix using pdist
# pdist computes the pairwise distances between all observations in a dataset.
# The dataset is represented by an array of points, where each row corresponds to a point in n-dimensional space.

# Example data (each row is a point in a 2D space)
X = np.array([[1, 2], [4, 6], [7, 8]])

# Compute pairwise Euclidean distances between points using pdist
pairwise_dist = distance.pdist(X, metric='euclidean')
print("Pairwise Euclidean Distances (using pdist):", pairwise_dist)

# Example: Converting Distance Vector to Square Distance Matrix using squareform
# squareform takes a condensed distance vector and converts it into a square form (distance matrix).
distance_matrix = distance.squareform(pairwise_dist)
print("Square Distance Matrix (using squareform):\n", distance_matrix)

# We can also use different distance metrics in pdist. Here's an example with the Manhattan (Cityblock) distance:

pairwise_manhattan = distance.pdist(X, metric='cityblock')
manhattan_distance_matrix = distance.squareform(pairwise_manhattan)
print("Manhattan Distance Matrix (using squareform):\n", manhattan_distance_matrix)


Pairwise Euclidean Distances (using pdist): [5.         8.48528137 3.60555128]
Square Distance Matrix (using squareform):
 [[0.         5.         8.48528137]
 [5.         0.         3.60555128]
 [8.48528137 3.60555128 0.        ]]
Manhattan Distance Matrix (using squareform):
 [[ 0.  7. 12.]
 [ 7.  0.  5.]
 [12.  5.  0.]]
