![Python for Physicist](https://github.com/scnilkunwar/Python-for-Physicist/blob/main/images/Banner.png?raw=true)

<div align="center">
    
![Numpy](https://raw.githubusercontent.com/numpy/numpy/main/branding/logo/primary/numpylogo.svg)
  <h1> Python for Physicist - NumPy Array</h1>
</div>

<a href="https://numpy.org/doc/stable/user/basics.html" 
style="display: inline-block; 
padding: 10px 20px; 
background-color: #4CAF50; 
color: white; 
text-align: center; 
text-decoration: none; 
border-radius: 5px;">NumPy Fundamentals</a>

## NumPy Arrays

### Creating Array
1. Creating Arrays
The core of NumPy is the ndarray (N-dimensional array), which can be created from Python lists or tuples using `np.array()`.

    ```python
    arr = np.array([1, 2, 3])
    print(arr)  # Output: [1 2 3]
    ```

In [1]:
import numpy as np

In [2]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

In [126]:
arr = np.array([1, 2, 3], dtype=float, ndmin=2)
arr

array([[1., 2., 3.]])

2. Multi-Dimensional Arrays
You can create multi-dimensional arrays by passing nested lists.

    ```python
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    print(arr)
    ```

In [127]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

- 2D array can be created using `np.matrix()`.

In [128]:
A = np.matrix([[1, 2, 3],
               [3, 4, 5],
               [4, 3, 7]])

3. Array Properties
    - **Shape**: The dimensions of the array.
    - **Size**: The total number of elements in the array.
    - **ndim**: The number of dimensions (axes).
    ```python
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    print(arr.shape)  # Output: (2, 3)
    print(arr.size)   # Output: 6
    print(arr.ndim)   # Output: 2
    ```

In [129]:
arr.size

3

In [130]:
arr2.size

6

In [131]:
arr2.shape

(2, 3)

There are more properties also. We can see all properties using `dir()` function.

## Array Initialization Functions
1. `np.zeros()`
Creates an array filled with zeros.

    ```python
    zeros = np.zeros((3, 3))
    print(zeros)
    ```

In [132]:
z = np.zeros(3, dtype=int)
z

array([0, 0, 0])

In [133]:
z2 = np.zeros((3, 2))
z2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

2. `np.ones()`
Creates an array filled with ones.

    ```python
    ones = np.ones((2, 3))
    print(ones)
    ```

In [134]:
a = np.ones((2, 2))
a

array([[1., 1.],
       [1., 1.]])

3. `np.full()`
Creates an array filled with a constant value.

    ```python
    full = np.full((2, 2), 7)
    print(full)
    ```

In [135]:
a = np.full((2, 3), 3)
a

array([[3, 3, 3],
       [3, 3, 3]])

In [136]:
np.full(4, 0, dtype=float)

array([0., 0., 0., 0.])

4. `np.arange()`
Creates an array with a sequence of numbers, similar to Python's range() function.

    ```python
    arange = np.arange(0, 10, 2)
    print(arange)  # Output: [0 2 4 6 8]
    ```

In [137]:
num = np.arange(5)
num

array([0, 1, 2, 3, 4])

In [138]:
np.arange(1, 9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [139]:
np.arange(-2, 4)

array([-2, -1,  0,  1,  2,  3])

In [140]:
np.arange(1, 10, 3)

array([1, 4, 7])

In [141]:
np.arange(10, 2, -1)

array([10,  9,  8,  7,  6,  5,  4,  3])

In [142]:
np.arange(1., 3. , 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

5. `np.linspace()`
Creates an array of equally spaced numbers between two specified values.

    ```python
    linspace = np.linspace(0, 1, 5)
    print(linspace)  # Output: [0.   0.25 0.5  0.75 1.  ]
    ```

In [143]:
np.linspace(6, 7, 10)

array([6.        , 6.11111111, 6.22222222, 6.33333333, 6.44444444,
       6.55555556, 6.66666667, 6.77777778, 6.88888889, 7.        ])

6. Random Arrays
`np.random.rand()` for random floats between 0 and 1.
`np.random.randint()` for random integers in a range.
    ```python
    rand_arr = np.random.rand(2, 3)
    print(rand_arr)
    rand_int = np.random.randint(0, 10, size=(2, 2))
    print(rand_int)
    ```

In [144]:
np.random.rand(3, 4)

array([[0.65327617, 0.44235134, 0.05169918, 0.85976805],
       [0.61761025, 0.84949395, 0.85495106, 0.98808816],
       [0.69231639, 0.99427662, 0.17360859, 0.8849657 ]])

In [145]:
np.random.randint(10, 100, (4, 2))

array([[48, 42],
       [94, 16],
       [45, 71],
       [49, 86]], dtype=int32)

7. `np.eye()`
Creates an array of identiy matrix.
    ```python
    I = np.eye(3)
    ```

In [146]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [147]:
np.eye(3, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [148]:
np.eye(6, 7, 2)

array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.]])

8. `np.diag()`
Creates an array of diagonal matrix
    ```python
    np.diag([1, 2, 3])
    ```

In [149]:
np.diag([1, 2, 4, 5])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [150]:
np.diag(np.random.randint(1, 10, 4), 1)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 9, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]], dtype=int32)

9. `zeros_like()` and `ones_like()`

    **zeros_like**: Create an array of zeros with the same shape as another array.
    
    **ones_like**: Create an array of ones with the same shape as another array.

In [151]:
arr = [[1, 2, 3],
       [3, 2, 4],
       [5, 6, 2]]
arr_zero = np.zeros_like(arr)
arr_zero

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Array Indexing and Slicing
1. Basic Indexing
You can access elements of arrays using indices.

    ```python
    arr = np.array([10, 20, 30, 40, 50])
    print(arr[2])  # Output: 30
    ```

In [152]:
arr = np.arange(1, 10, 2)
arr

array([1, 3, 5, 7, 9])

In [153]:
print(arr[2])

5


2. Multi-dimensional Indexing
For multi-dimensional arrays, use comma-separated indices.

    ```python
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    print(arr[0, 2])  # Output: 3
    ```

In [154]:
arr2 = np.random.randint(1, 20, (3, 4))
print(arr2)

[[15  9 13 15]
 [ 1  9  5 15]
 [ 5 11  5 18]]


In [155]:
arr2[1, 3]

np.int32(15)

3. Slicing
Slicing allows you to extract subarrays.

    ```python
    arr = np.array([10, 20, 30, 40, 50])
    print(arr[1:4])  # Output: [20 30 40]
    ```

In [156]:
arr[1:3]

array([3, 5])

In [157]:
arr[:3]

array([1, 3, 5])

In [158]:
arr[::-1]

array([9, 7, 5, 3, 1])

4. For 2D arrays:

    ```python
    arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    print(arr[1:, 1:])  # Output: [[5 6] [8 9]]
    ```

In [159]:
print(arr2)

[[15  9 13 15]
 [ 1  9  5 15]
 [ 5 11  5 18]]


In [160]:
#forst column
print(arr2[:, 0])

[15  1  5]


In [161]:
#2nd Row
print(arr2[1, :])

[ 1  9  5 15]


## Array Operations
1. Element-wise Operations
NumPy allows element-wise operations, such as addition, subtraction, multiplication, and division.

In [162]:
#operations with scalers
arr = np.array([1, 2, 3])
arr2 = arr * 3
arr2

array([3, 6, 9])

In [163]:
#operations with array
arr_a = np.array([2, 3, 4])
arr_b = np.array([3, 4, 5])
arr_c = arr_a - arr_b
arr_c

array([-1, -1, -1])

We can use logical operations also.

2. Reshaping Arrays
You can change the shape of arrays using reshape().

    ```python
        arr = np.array([1, 2, 3, 4, 5, 6])
        reshaped = arr.reshape((2, 3))
        print(reshaped)
    ```

In [164]:
my_array = np.random.randint(1, 20, 12)
print(my_array)

[17 16  5 15 12 12 16 18  2 10 10  7]


In [165]:
my_arr_2d = np.reshape(my_array, (3, 4))
print(my_arr_2d)

[[17 16  5 15]
 [12 12 16 18]
 [ 2 10 10  7]]


3. `np.transpose()`
This function reverses or permutes the axes of an array. For a 2D array, it swaps rows with columns.
```python
    np.transpose(a)

In [166]:
b = np.array([[1, 2, 3], [4, 5, 6]])

# Transposing the array
transposed_b = np.transpose(b)
print(transposed_b)

[[1 4]
 [2 5]
 [3 6]]


4. `np.ravel()`
This function returns a 1D array, or flattened array, from a multidimensional input array. It returns a view of the array, meaning that changes to the flattened array may modify the original array (depending on memory layout).

In [167]:
c = np.array([[1, 2, 3], [4, 5, 6]])

# Flattening the array
flattened_c = np.ravel(c)
print(flattened_c)

[1 2 3 4 5 6]


5. `np.flatten()`
Similar to np.ravel(), but it returns a copy of the array rather than a view. Modifying the flattened array does not affect the original array.

In [168]:
d = np.array([[1, 2], [3, 4]])

# Flattening the array
flattened_d = d.flatten()
print(flattened_d)

[1 2 3 4]


6. **Broadcasting**: Broadcasting allows NumPy to perform element-wise operations on arrays with different shapes.

    ```python
        arr1 = np.array([1, 2, 3])
        arr2 = np.array([[1], [2], [3]])
        result = arr1 + arr2
        print(result)
        # Output:
        # [[2 3 4]
        #  [3 4 5]
        #  [4 5 6]]
    ```

In [169]:
arr_1d = np.random.randint(1, 20, 3)
arr_2d = np.random.randint(1, 20, (1, 3))
print('1D array =', arr_1d)
print('2D array\n', arr_2d)

1D array = [3 6 3]
2D array
 [[17 17  7]]


In [170]:
arr_1d + arr_2d

array([[20, 23, 10]], dtype=int32)

## Advanced Topics
1. Boolean Indexing
Boolean indexing allows you to filter arrays based on conditions.

    ```python
    arr = np.array([10, 20, 30, 40, 50])
    print(arr[arr > 25])  # Output: [30 40 50]
    ```

In [171]:
my_array = np.random.randint(1, 20, 12)
print(my_array)

[18 16 17 18  8 13  1 10 18 12 14  7]


In [172]:
bool_index = my_array > 10
bool_index

array([ True,  True,  True,  True, False,  True, False, False,  True,
        True,  True, False])

In [173]:
print(my_array[bool_index])

[18 16 17 18 13 18 12 14]


#### Question
Given an array, find out the elements only divisible by 3 or 5

In [174]:
arr = np.random.randint(1, 200, 50)
print(arr)

[ 20 159  15 124  39  53   5  44  18  47 142  15   6 190  57 166 136 169
 142  40  27  22 150  49 140  26 100  92 173 182  64  53 106 184 130 115
 129 174 145 188  86  72  25 112  74 183 108 124 129 104]


In [175]:
arr_3_5 = arr[(arr % 3 == 0) | (arr % 5 == 0)]
print(arr_3_5)

[ 20 159  15  39   5  18  15   6 190  57  40  27 150 140 100 130 115 129
 174 145  72  25 183 108 129]


2. Fancy Indexing
Fancy indexing refers to using arrays of indices to access elements.

    ```python
    arr = np.array([10, 20, 30, 40, 50])
    indices = [0, 2, 4]
    print(arr[indices])  # Output: [10 30 50]
    ```

In [176]:
arr = np.array([])

3. Array Copying
- Shallow Copy: Changes in the original array affect the copied array.

In [177]:
arr = np.array([1, 2, 3])
copy = arr.view()
arr[0] = 10
print(copy)  # Output: [10  2  3]

[10  2  3]


- Deep Copy: Changes in the original array do not affect the copied array.

In [178]:
arr = np.array([1, 2, 3])
copy = arr.copy()
arr[0] = 10
print(copy)  # Output: [1 2 3]

[1 2 3]


- `np.unique()`: Find the unique elements of an array. Returns the sorted unique elements of an array. There are three optional outputs in addition to the unique elements

In [179]:
help(np.unique)

Help on _ArrayFunctionDispatcher in module numpy:

unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None, *, equal_nan=True)
    Find the unique elements of an array.

    Returns the sorted unique elements of an array. There are three optional
    outputs in addition to the unique elements:

    * the indices of the input array that give the unique values
    * the indices of the unique array that reconstruct the input array
    * the number of times each unique value comes up in the input array

    Parameters
    ----------
    ar : array_like
        Input array. Unless `axis` is specified, this will be flattened if it
        is not already 1-D.
    return_index : bool, optional
        If True, also return the indices of `ar` (along the specified axis,
        if provided, or in the flattened array) that result in the unique array.
    return_inverse : bool, optional
        If True, also return the indices of the unique array (for the specified
    

## Sorting, Searching, and Counting in Arrays

### Sorting

- **`sort(a, axis, kind, order, stable)`**  
  Return a sorted copy of an array.

- **`ndarray.sort(axis, kind, order)`**  
  Sort an array in-place.

In [180]:
a = np.random.randint(1, 20, 10)
print(a)

[ 1 16 12 14  9 17 13 11 13  5]


In [181]:
a_sorted = np.sort(a)
print(a_sorted)

[ 1  5  9 11 12 13 13 14 16 17]


In [182]:
a.sort()
a

array([ 1,  5,  9, 11, 12, 13, 13, 14, 16, 17], dtype=int32)

In [183]:
A = np.random.randint(1, 20, (4, 5))
print(A)

[[ 8 13 17  1  8]
 [ 8 16 15 13  8]
 [ 5 19  4  5  5]
 [ 9  7 11 18  3]]


In [184]:
A_sorted = np.sort(A, 0)
A_sorted

array([[ 5,  7,  4,  1,  3],
       [ 8, 13, 11,  5,  5],
       [ 8, 16, 15, 13,  8],
       [ 9, 19, 17, 18,  8]], dtype=int32)

- **`lexsort(keys, axis)`**  
  Perform an indirect stable sort using a sequence of keys.



In [185]:
names = np.array(['Umesh', 'Sunil', 'Sanam', 'Sandip'])
ages = np.array([22, 25, 23, 23])
sorted_index = np.lexsort((names, ages))
sorted_names = names[sorted_index]
print(sorted_names)

['Umesh' 'Sanam' 'Sandip' 'Sunil']


- **`argsort(a, axis, kind, order, stable)`**  
  Returns the indices that would sort an array.

In [186]:
a = np.array([1, 4, 2, 7, 9, 3])
index = np.argsort(a)
print(a[index])

[1 2 3 4 7 9]


- **`sort_complex(a)`**  
  Sort a complex array using the real part first, then the imaginary part.



In [187]:
c = np.array([1 + 4j, -3 + 4j, 7 - 4j, 9 + 8j, 1 + 3j])
print(c)

[ 1.+4.j -3.+4.j  7.-4.j  9.+8.j  1.+3.j]


In [188]:
c_sorted = np.sort_complex(c)
c_sorted

array([-3.+4.j,  1.+3.j,  1.+4.j,  7.-4.j,  9.+8.j])

### Searching

- **`argmax(a, axis, out, keepdims)`**  
  Returns the indices of the maximum values along an axis.


In [213]:
a = np.random.randint(0, 20, (3, 4))
a

array([[ 0, 17,  6,  6],
       [18, 11, 13, 16],
       [13, 18,  8, 18]], dtype=int32)

In [197]:
indices = np.argmax(a, 1)
indices

array([3, 1, 1])


- **`nanargmax(a, axis, out, keepdims)`**  
  Return the indices of the maximum values in the specified axis ignoring NaNs.

- **`argmin(a, axis, out, keepdims)`**  
  Returns the indices of the minimum values along an axis.

- **`nanargmin(a, axis, out, keepdims)`**  
  Return the indices of the minimum values in the specified axis ignoring NaNs.


- **`argwhere(a)`**  
  Find the indices of array elements that are non-zero, grouped by element.

In [209]:
print(a)
indices = np.argwhere(a < 5)
print(indices)

[[ 1  6 10 16]
 [ 6  7  1  1]
 [ 3 13  5 12]]
[[0 0]
 [1 2]
 [1 3]
 [2 0]]


- **`nonzero(a)`**  
  Return the indices of the elements that are non-zero.

In [215]:
indices = np.nonzero(a)
print(a[indices])

[17  6  6 18 11 13 16 13 18  8 18]


- **`flatnonzero(a)`**  
  Return indices that are non-zero in the flattened version of a.

In [216]:
np.flatnonzero(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- **`where(condition, x, y)`**  
  Return elements chosen from x or y depending on condition.

In [231]:
np.where(a == 11)

(array([1]), array([1]))

- **`extract(condition, arr)`**  
  Return the elements of an array that satisfy some condition.

In [233]:
np.extract(a > 10, a)

array([17, 18, 11, 13, 16, 13, 18, 18], dtype=int32)

### Counting

- **`count_nonzero(a, axis, keepdims)`**  
  Counts the number of non-zero values in the array `a`.

In [234]:
np.count_nonzero(a)

11

### Array Manipulation
- `np.concatenate((a, b), axis)`: Concatenates arrays along a specified axis.
- `np.split(array, indices_or_sections, axis)`: Splits an array into multiple sub-arrays.

In [260]:
from numpy import concat


a = np.random.random((3, 4))
b = np.random.random((3, 4))
print(a)
print(b)
concatenated = np.concatenate((a, b), axis=0)
print(concatenated)

[[0.01019253 0.79362143 0.08405966 0.65030371]
 [0.28579575 0.61771646 0.14394879 0.38513511]
 [0.21345584 0.68973131 0.03967527 0.304256  ]]
[[0.23021143 0.39630454 0.43338391 0.88235026]
 [0.89806829 0.36719667 0.43896217 0.68906584]
 [0.90212067 0.34633289 0.49274852 0.38031603]]
[[0.01019253 0.79362143 0.08405966 0.65030371]
 [0.28579575 0.61771646 0.14394879 0.38513511]
 [0.21345584 0.68973131 0.03967527 0.304256  ]
 [0.23021143 0.39630454 0.43338391 0.88235026]
 [0.89806829 0.36719667 0.43896217 0.68906584]
 [0.90212067 0.34633289 0.49274852 0.38031603]]


In [264]:
splited = np.split(concatenated, [2, 3])
splited

[array([[0.01019253, 0.79362143, 0.08405966, 0.65030371],
        [0.28579575, 0.61771646, 0.14394879, 0.38513511]]),
 array([[0.21345584, 0.68973131, 0.03967527, 0.304256  ]]),
 array([[0.23021143, 0.39630454, 0.43338391, 0.88235026],
        [0.89806829, 0.36719667, 0.43896217, 0.68906584],
        [0.90212067, 0.34633289, 0.49274852, 0.38031603]])]