## NumPy Arrays
1. Creating Arrays
The core of NumPy is the ndarray (N-dimensional array), which can be created from Python lists or tuples using `np.array()`.

    ```python
    arr = np.array([1, 2, 3])
    print(arr)  # Output: [1 2 3]
    ```

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3], dtype=float, ndmin=2)
arr

array([[1., 2., 3.]])

2. Multi-Dimensional Arrays
You can create multi-dimensional arrays by passing nested lists.

    ```python
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    print(arr)
    ```

In [3]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

3. Array Properties
    - **Shape**: The dimensions of the array.
    - **Size**: The total number of elements in the array.
    - **ndim**: The number of dimensions (axes).
    ```python
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    print(arr.shape)  # Output: (2, 3)
    print(arr.size)   # Output: 6
    print(arr.ndim)   # Output: 2
    ```

In [4]:
arr.size

3

In [5]:
arr2.size

6

In [6]:
arr2.shape

(2, 3)

There are more properties also. We can see all properties using `dir()` function.

## Array Initialization Functions
1. `np.zeros()`
Creates an array filled with zeros.

    ```python
    zeros = np.zeros((3, 3))
    print(zeros)
    ```

In [7]:
z = np.zeros(3, dtype=int)
z

array([0, 0, 0])

In [8]:
z2 = np.zeros((3, 2))
z2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

2. `np.ones()`
Creates an array filled with ones.

    ```python
    ones = np.ones((2, 3))
    print(ones)
    ```

In [9]:
a = np.ones((2, 2))
a

array([[1., 1.],
       [1., 1.]])

3. `np.full()`
Creates an array filled with a constant value.

    ```python
    full = np.full((2, 2), 7)
    print(full)
    ```

In [10]:
a = np.full((2, 3), 3)
a

array([[3, 3, 3],
       [3, 3, 3]])

In [11]:
np.full(4, 0, dtype=float)

array([0., 0., 0., 0.])

4. `np.arange()`
Creates an array with a sequence of numbers, similar to Python's range() function.

    ```python
    arange = np.arange(0, 10, 2)
    print(arange)  # Output: [0 2 4 6 8]
    ```

In [12]:
num = np.arange(5)
num

array([0, 1, 2, 3, 4])

In [13]:
np.arange(1, 9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np.arange(-2, 4)

array([-2, -1,  0,  1,  2,  3])

In [15]:
np.arange(1, 10, 3)

array([1, 4, 7])

In [16]:
np.arange(10, 2, -1)

array([10,  9,  8,  7,  6,  5,  4,  3])

In [17]:
np.arange(1., 3. , 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

5. `np.linspace()`
Creates an array of equally spaced numbers between two specified values.

    ```python
    linspace = np.linspace(0, 1, 5)
    print(linspace)  # Output: [0.   0.25 0.5  0.75 1.  ]
    ```

In [18]:
np.linspace(6, 7, 10)

array([6.        , 6.11111111, 6.22222222, 6.33333333, 6.44444444,
       6.55555556, 6.66666667, 6.77777778, 6.88888889, 7.        ])

6. Random Arrays
`np.random.rand()` for random floats between 0 and 1.
`np.random.randint()` for random integers in a range.
    ```python
    rand_arr = np.random.rand(2, 3)
    print(rand_arr)
    rand_int = np.random.randint(0, 10, size=(2, 2))
    print(rand_int)
    ```

In [19]:
np.random.rand(3, 4)

array([[0.30429552, 0.11913128, 0.21661728, 0.07665877],
       [0.72831816, 0.03930903, 0.19528819, 0.48743427],
       [0.30753119, 0.48317423, 0.15970859, 0.15665383]])

In [30]:
np.random.randint(10, 100, (4, 2))

array([[39, 62],
       [64, 45],
       [39, 14],
       [88, 83]], dtype=int32)

7. `np.eye()`
Creates an array of identiy matrix.
    ```python
    I = np.eye(3)
    ```

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.eye(3, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [23]:
np.eye(6, 7, 2)

array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.]])

8. `np.diag()`
Creates an array of diagonal matrix
    ```python
    np.diag([1, 2, 3])
    ```

In [24]:
np.diag([1, 2, 4, 5])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [25]:
np.diag(np.random.randint(1, 10, 4), 1)

array([[0, 2, 0, 0, 0],
       [0, 0, 7, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]], dtype=int32)

9. `zeros_like()` and `ones_like()`

    **zeros_like**: Create an array of zeros with the same shape as another array.
    
    **ones_like**: Create an array of ones with the same shape as another array.

In [26]:
arr = [[1, 2, 3],
       [3, 2, 4],
       [5, 6, 2]]
arr_zero = np.zeros_like(arr)
arr_zero

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Array Indexing and Slicing
1. Basic Indexing
You can access elements of arrays using indices.

    ```python
    arr = np.array([10, 20, 30, 40, 50])
    print(arr[2])  # Output: 30
    ```

In [36]:
arr = np.arange(1, 10, 2)
arr

array([1, 3, 5, 7, 9])

In [37]:
print(arr[2])

5


2. Multi-dimensional Indexing
For multi-dimensional arrays, use comma-separated indices.

    ```python
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    print(arr[0, 2])  # Output: 3
    ```

In [38]:
arr2 = np.random.randint(1, 20, (3, 4))
print(arr2)

[[10  5 17 17]
 [ 1  1  1 15]
 [ 1  7  4 11]]


In [39]:
arr2[1, 3]

np.int32(15)

3. Slicing
Slicing allows you to extract subarrays.

    ```python
    arr = np.array([10, 20, 30, 40, 50])
    print(arr[1:4])  # Output: [20 30 40]
    ```

In [40]:
arr[1:3]

array([3, 5])

In [41]:
arr[:3]

array([1, 3, 5])

In [42]:
arr[::-1]

array([9, 7, 5, 3, 1])

4. For 2D arrays:

    ```python
    arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    print(arr[1:, 1:])  # Output: [[5 6] [8 9]]
    ```

## Array Operations
1. Element-wise Operations
NumPy allows element-wise operations, such as addition, subtraction, multiplication, and division.

    ```python
    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])
    print(arr1 + arr2)  # Output: [5 7 9]
    ```
2. Matrix Operations
Matrix multiplication can be done using np.dot() or the @ operator.

    ```python
    mat1 = np.array([[1, 2], [3, 4]])
    mat2 = np.array([[5, 6], [7, 8]])
    print(np.dot(mat1, mat2))  # Output: [[19 22] [43 50]]
    ```
3. Aggregation Functions
NumPy provides various functions for array aggregation:
`np.sum()`: Sum of array elements.
`np.mean()`: Mean of array elements.
`np.max()`: Maximum element in an array.
`np.min()`: Minimum element in an array.
    ```python
        arr = np.array([1, 2, 3, 4])
        print(np.sum(arr))  # Output: 10
        print(np.mean(arr))  # Output: 2.5
    ```
4. Reshaping Arrays
You can change the shape of arrays using reshape().

    ```python
        arr = np.array([1, 2, 3, 4, 5, 6])
        reshaped = arr.reshape((2, 3))
        print(reshaped)
    ```
5. Broadcasting
Broadcasting allows NumPy to perform element-wise operations on arrays with different shapes.

    ```python
        arr1 = np.array([1, 2, 3])
        arr2 = np.array([[1], [2], [3]])
        result = arr1 + arr2
        print(result)
        # Output:
        # [[2 3 4]
        #  [3 4 5]
        #  [4 5 6]]
    ```

## Advanced Topics
1. Boolean Indexing
Boolean indexing allows you to filter arrays based on conditions.

    ```python
    arr = np.array([10, 20, 30, 40, 50])
    print(arr[arr > 25])  # Output: [30 40 50]
    ```
2. Fancy Indexing
Fancy indexing refers to using arrays of indices to access elements.

    ```python
    arr = np.array([10, 20, 30, 40, 50])
    indices = [0, 2, 4]
    print(arr[indices])  # Output: [10 30 50]
    ```
3. Array Copying
- Shallow Copy: Changes in the original array affect the copied array.

    ```python
        arr = np.array([1, 2, 3])
        copy = arr.view()
        arr[0] = 10
        print(copy)  # Output: [10  2  3]
    ```
- Deep Copy: Changes in the original array do not affect the copied array.

    ```python
    arr = np.array([1, 2, 3])
    copy = arr.copy()
    arr[0] = 10
    print(copy)  # Output: [1 2 3]
    ```