<div align="center">
    
![Numpy](https://raw.githubusercontent.com/numpy/numpy/main/branding/logo/primary/numpylogo.svg)
  <h1> Python for Physicist - Numpy Array</h1>
</div>

<a href="https://numpy.org/doc/stable/user/basics.html" 
style="display: inline-block; 
padding: 10px 20px; 
background-color: #4CAF50; 
color: white; 
text-align: center; 
text-decoration: none; 
border-radius: 5px;">NumPy Fundamentals</a>

## NumPy Arrays

### Creating Array
1. Creating Arrays
The core of NumPy is the ndarray (N-dimensional array), which can be created from Python lists or tuples using `np.array()`.

    ```python
    arr = np.array([1, 2, 3])
    print(arr)  # Output: [1 2 3]
    ```

In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3], dtype=float, ndmin=2)
arr

array([[1., 2., 3.]])

2. Multi-Dimensional Arrays
You can create multi-dimensional arrays by passing nested lists.

    ```python
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    print(arr)
    ```

In [4]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

3. Array Properties
    - **Shape**: The dimensions of the array.
    - **Size**: The total number of elements in the array.
    - **ndim**: The number of dimensions (axes).
    ```python
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    print(arr.shape)  # Output: (2, 3)
    print(arr.size)   # Output: 6
    print(arr.ndim)   # Output: 2
    ```

In [5]:
arr.size

3

In [6]:
arr2.size

6

In [7]:
arr2.shape

(2, 3)

There are more properties also. We can see all properties using `dir()` function.

## Array Initialization Functions
1. `np.zeros()`
Creates an array filled with zeros.

    ```python
    zeros = np.zeros((3, 3))
    print(zeros)
    ```

In [8]:
z = np.zeros(3, dtype=int)
z

array([0, 0, 0])

In [9]:
z2 = np.zeros((3, 2))
z2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

2. `np.ones()`
Creates an array filled with ones.

    ```python
    ones = np.ones((2, 3))
    print(ones)
    ```

In [10]:
a = np.ones((2, 2))
a

array([[1., 1.],
       [1., 1.]])

3. `np.full()`
Creates an array filled with a constant value.

    ```python
    full = np.full((2, 2), 7)
    print(full)
    ```

In [11]:
a = np.full((2, 3), 3)
a

array([[3, 3, 3],
       [3, 3, 3]])

In [12]:
np.full(4, 0, dtype=float)

array([0., 0., 0., 0.])

4. `np.arange()`
Creates an array with a sequence of numbers, similar to Python's range() function.

    ```python
    arange = np.arange(0, 10, 2)
    print(arange)  # Output: [0 2 4 6 8]
    ```

In [13]:
num = np.arange(5)
num

array([0, 1, 2, 3, 4])

In [14]:
np.arange(1, 9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
np.arange(-2, 4)

array([-2, -1,  0,  1,  2,  3])

In [16]:
np.arange(1, 10, 3)

array([1, 4, 7])

In [17]:
np.arange(10, 2, -1)

array([10,  9,  8,  7,  6,  5,  4,  3])

In [18]:
np.arange(1., 3. , 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

5. `np.linspace()`
Creates an array of equally spaced numbers between two specified values.

    ```python
    linspace = np.linspace(0, 1, 5)
    print(linspace)  # Output: [0.   0.25 0.5  0.75 1.  ]
    ```

In [19]:
np.linspace(6, 7, 10)

array([6.        , 6.11111111, 6.22222222, 6.33333333, 6.44444444,
       6.55555556, 6.66666667, 6.77777778, 6.88888889, 7.        ])

6. Random Arrays
`np.random.rand()` for random floats between 0 and 1.
`np.random.randint()` for random integers in a range.
    ```python
    rand_arr = np.random.rand(2, 3)
    print(rand_arr)
    rand_int = np.random.randint(0, 10, size=(2, 2))
    print(rand_int)
    ```

In [20]:
np.random.rand(3, 4)

array([[0.58053001, 0.95530789, 0.64458761, 0.04545767],
       [0.94481187, 0.8930565 , 0.63002415, 0.59684721],
       [0.30450931, 0.43334293, 0.77928303, 0.80073532]])

In [21]:
np.random.randint(10, 100, (4, 2))

array([[85, 67],
       [21, 73],
       [42, 19],
       [96, 32]], dtype=int32)

7. `np.eye()`
Creates an array of identiy matrix.
    ```python
    I = np.eye(3)
    ```

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.eye(3, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [24]:
np.eye(6, 7, 2)

array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.]])

8. `np.diag()`
Creates an array of diagonal matrix
    ```python
    np.diag([1, 2, 3])
    ```

In [25]:
np.diag([1, 2, 4, 5])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [26]:
np.diag(np.random.randint(1, 10, 4), 1)

array([[0, 8, 0, 0, 0],
       [0, 0, 9, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0]], dtype=int32)

9. `zeros_like()` and `ones_like()`

    **zeros_like**: Create an array of zeros with the same shape as another array.
    
    **ones_like**: Create an array of ones with the same shape as another array.

In [27]:
arr = [[1, 2, 3],
       [3, 2, 4],
       [5, 6, 2]]
arr_zero = np.zeros_like(arr)
arr_zero

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Array Indexing and Slicing
1. Basic Indexing
You can access elements of arrays using indices.

    ```python
    arr = np.array([10, 20, 30, 40, 50])
    print(arr[2])  # Output: 30
    ```

In [28]:
arr = np.arange(1, 10, 2)
arr

array([1, 3, 5, 7, 9])

In [29]:
print(arr[2])

5


2. Multi-dimensional Indexing
For multi-dimensional arrays, use comma-separated indices.

    ```python
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    print(arr[0, 2])  # Output: 3
    ```

In [30]:
arr2 = np.random.randint(1, 20, (3, 4))
print(arr2)

[[12 16 13  2]
 [12  4  7  4]
 [18  4 16 14]]


In [31]:
arr2[1, 3]

np.int32(4)

3. Slicing
Slicing allows you to extract subarrays.

    ```python
    arr = np.array([10, 20, 30, 40, 50])
    print(arr[1:4])  # Output: [20 30 40]
    ```

In [32]:
arr[1:3]

array([3, 5])

In [33]:
arr[:3]

array([1, 3, 5])

In [34]:
arr[::-1]

array([9, 7, 5, 3, 1])

4. For 2D arrays:

    ```python
    arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    print(arr[1:, 1:])  # Output: [[5 6] [8 9]]
    ```

In [35]:
print(arr2)

[[12 16 13  2]
 [12  4  7  4]
 [18  4 16 14]]


In [36]:
#forst column
print(arr2[:, 0])

[12 12 18]


In [37]:
#2nd Row
print(arr2[1, :])

[12  4  7  4]


## Array Operations
1. Element-wise Operations
NumPy allows element-wise operations, such as addition, subtraction, multiplication, and division.

In [38]:
#operations with scalers
arr = np.array([1, 2, 3])
arr2 = arr * 3
arr2

array([3, 6, 9])

In [39]:
#operations with array
arr_a = np.array([2, 3, 4])
arr_b = np.array([3, 4, 5])
arr_c = arr_a - arr_b
arr_c

array([-1, -1, -1])

We can use logical operations also.

2. Reshaping Arrays
You can change the shape of arrays using reshape().

    ```python
        arr = np.array([1, 2, 3, 4, 5, 6])
        reshaped = arr.reshape((2, 3))
        print(reshaped)
    ```

In [40]:
my_array = np.random.randint(1, 20, 12)
print(my_array)

[ 6  4 14 10 17 17  7  1  4 19 17 12]


In [41]:
my_arr_2d = np.reshape(my_array, (3, 4))
print(my_arr_2d)

[[ 6  4 14 10]
 [17 17  7  1]
 [ 4 19 17 12]]


3. `np.transpose()`
This function reverses or permutes the axes of an array. For a 2D array, it swaps rows with columns.
```python
    np.transpose(a)

In [42]:
b = np.array([[1, 2, 3], [4, 5, 6]])

# Transposing the array
transposed_b = np.transpose(b)
print(transposed_b)

[[1 4]
 [2 5]
 [3 6]]


4. `np.ravel()`
This function returns a 1D array, or flattened array, from a multidimensional input array. It returns a view of the array, meaning that changes to the flattened array may modify the original array (depending on memory layout).

In [53]:
c = np.array([[1, 2, 3], [4, 5, 6]])

# Flattening the array
flattened_c = np.ravel(c)
print(flattened_c)

[1 2 3 4 5 6]


5. `np.flatten()`
Similar to np.ravel(), but it returns a copy of the array rather than a view. Modifying the flattened array does not affect the original array.

In [54]:
d = np.array([[1, 2], [3, 4]])

# Flattening the array
flattened_d = d.flatten()
print(flattened_d)

[1 2 3 4]


6. **Broadcasting**: Broadcasting allows NumPy to perform element-wise operations on arrays with different shapes.

    ```python
        arr1 = np.array([1, 2, 3])
        arr2 = np.array([[1], [2], [3]])
        result = arr1 + arr2
        print(result)
        # Output:
        # [[2 3 4]
        #  [3 4 5]
        #  [4 5 6]]
    ```

In [43]:
arr_1d = np.random.randint(1, 20, 3)
arr_2d = np.random.randint(1, 20, (1, 3))
print('1D array =', arr_1d)
print('2D array\n', arr_2d)

1D array = [15  4  7]
2D array
 [[ 2 14  2]]


In [44]:
arr_1d + arr_2d

array([[17, 18,  9]], dtype=int32)

## Advanced Topics
1. Boolean Indexing
Boolean indexing allows you to filter arrays based on conditions.

    ```python
    arr = np.array([10, 20, 30, 40, 50])
    print(arr[arr > 25])  # Output: [30 40 50]
    ```

In [45]:
my_array = np.random.randint(1, 20, 12)
print(my_array)

[13  5 17  8 15  4  2 19  5  1 19 19]


In [46]:
bool_index = my_array > 10
bool_index

array([ True, False,  True, False,  True, False, False,  True, False,
       False,  True,  True])

In [47]:
print(my_array[bool_index])

[13 17 15 19 19 19]


#### Question
Given an array, find out the elements only divisible by 3 or 5

In [59]:
arr = np.random.randint(1, 200, 50)
print(arr)

[  9  75 138  48 144  37 132 175 114  61 154  37  22 195  16 120  84 196
  53 103  94  38  40 185 186  15 146 120 194  85  72   6  78   7  18  63
 140 199 141  66 173   1  17  25  75 139  83 133  24  53]


In [61]:
arr_3_5 = arr[(arr % 3 == 0) | (arr % 5 == 0)]
print(arr_3_5)

[  9  75 138  48 144 132 175 114 195 120  84  40 185 186  15 120  85  72
   6  78  18  63 140 141  66  25  75  24]


2. Fancy Indexing
Fancy indexing refers to using arrays of indices to access elements.

    ```python
    arr = np.array([10, 20, 30, 40, 50])
    indices = [0, 2, 4]
    print(arr[indices])  # Output: [10 30 50]
    ```

In [50]:
arr = np.array([])

3. Array Copying
- Shallow Copy: Changes in the original array affect the copied array.

    ```python
        arr = np.array([1, 2, 3])
        copy = arr.view()
        arr[0] = 10
        print(copy)  # Output: [10  2  3]
    ```
- Deep Copy: Changes in the original array do not affect the copied array.

    ```python
    arr = np.array([1, 2, 3])
    copy = arr.copy()
    arr[0] = 10
    print(copy)  # Output: [1 2 3]
    ```

- `np.unique()`: Find the unique elements of an array. Returns the sorted unique elements of an array. There are three optional outputs in addition to the unique elements