## NumPy Arrays
1. Creating Arrays
The core of NumPy is the ndarray (N-dimensional array), which can be created from Python lists or tuples using `np.array()`.

    ```python
    arr = np.array([1, 2, 3])
    print(arr)  # Output: [1 2 3]
    ```
2. Multi-Dimensional Arrays
You can create multi-dimensional arrays by passing nested lists.

    ```python
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    print(arr)
    ```
3. Array Properties
    - **Shape**: The dimensions of the array.
    - **Size**: The total number of elements in the array.
    - **ndim**: The number of dimensions (axes).
    ```python
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    print(arr.shape)  # Output: (2, 3)
    print(arr.size)   # Output: 6
    print(arr.ndim)   # Output: 2
    ```
## Array Initialization Functions
1. `np.zeros()`
Creates an array filled with zeros.

    ```python
    zeros = np.zeros((3, 3))
    print(zeros)
    ```
2. `np.ones()`
Creates an array filled with ones.

    ```python
    ones = np.ones((2, 3))
    print(ones)
    ```
3. `np.full()`
Creates an array filled with a constant value.

    ```python
    full = np.full((2, 2), 7)
    print(full)
    ```
4. `np.arange()`
Creates an array with a sequence of numbers, similar to Python's range() function.

    ```python
    arange = np.arange(0, 10, 2)
    print(arange)  # Output: [0 2 4 6 8]
    ```
5. `np.linspace()`
Creates an array of equally spaced numbers between two specified values.

    ```python
    linspace = np.linspace(0, 1, 5)
    print(linspace)  # Output: [0.   0.25 0.5  0.75 1.  ]
    ```
6. Random Arrays
`np.random.rand()` for random floats between 0 and 1.
`np.random.randint()` for random integers in a range.
    ```python
    rand_arr = np.random.rand(2, 3)
    print(rand_arr)
    rand_int = np.random.randint(0, 10, size=(2, 2))
    print(rand_int)
    ```
## Array Indexing and Slicing
1. Basic Indexing
You can access elements of arrays using indices.

    ```python
    arr = np.array([10, 20, 30, 40, 50])
    print(arr[2])  # Output: 30
    ```
2. Multi-dimensional Indexing
For multi-dimensional arrays, use comma-separated indices.

    ```python
    arr = np.array([[1, 2, 3], [4, 5, 6]])
    print(arr[0, 2])  # Output: 3
    ```
3. Slicing
Slicing allows you to extract subarrays.

    ```python
    arr = np.array([10, 20, 30, 40, 50])
    print(arr[1:4])  # Output: [20 30 40]
    ```
4. For 2D arrays:

    ```python
    arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    print(arr[1:, 1:])  # Output: [[5 6] [8 9]]
    ```
## Array Operations
1. Element-wise Operations
NumPy allows element-wise operations, such as addition, subtraction, multiplication, and division.

    ```python
    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])
    print(arr1 + arr2)  # Output: [5 7 9]
    ```
2. Matrix Operations
Matrix multiplication can be done using np.dot() or the @ operator.

    ```python
    mat1 = np.array([[1, 2], [3, 4]])
    mat2 = np.array([[5, 6], [7, 8]])
    print(np.dot(mat1, mat2))  # Output: [[19 22] [43 50]]
    ```
3. Aggregation Functions
NumPy provides various functions for array aggregation:
`np.sum()`: Sum of array elements.
`np.mean()`: Mean of array elements.
`np.max()`: Maximum element in an array.
`np.min()`: Minimum element in an array.
    ```python
        arr = np.array([1, 2, 3, 4])
        print(np.sum(arr))  # Output: 10
        print(np.mean(arr))  # Output: 2.5
    ```
4. Reshaping Arrays
You can change the shape of arrays using reshape().

    ```python
        arr = np.array([1, 2, 3, 4, 5, 6])
        reshaped = arr.reshape((2, 3))
        print(reshaped)
    ```
5. Broadcasting
Broadcasting allows NumPy to perform element-wise operations on arrays with different shapes.

    ```python
        arr1 = np.array([1, 2, 3])
        arr2 = np.array([[1], [2], [3]])
        result = arr1 + arr2
        print(result)
        # Output:
        # [[2 3 4]
        #  [3 4 5]
        #  [4 5 6]]
    ```
## Advanced Topics
1. Boolean Indexing
Boolean indexing allows you to filter arrays based on conditions.

    ```python
    arr = np.array([10, 20, 30, 40, 50])
    print(arr[arr > 25])  # Output: [30 40 50]
    ```
2. Fancy Indexing
Fancy indexing refers to using arrays of indices to access elements.

    ```python
    arr = np.array([10, 20, 30, 40, 50])
    indices = [0, 2, 4]
    print(arr[indices])  # Output: [10 30 50]
    ```
3. Array Copying
- Shallow Copy: Changes in the original array affect the copied array.

    ```python
        arr = np.array([1, 2, 3])
        copy = arr.view()
        arr[0] = 10
        print(copy)  # Output: [10  2  3]
    ```
- Deep Copy: Changes in the original array do not affect the copied array.

    ```python
    arr = np.array([1, 2, 3])
    copy = arr.copy()
    arr[0] = 10
    print(copy)  # Output: [1 2 3]
    ```