<div align="center">
    
![Numpy](https://raw.githubusercontent.com/numpy/numpy/main/branding/logo/primary/numpylogo.svg)
  <h1> Python for Physicist - Numpy Linear Algebra</h1>
</div>

<a href="https://numpy.org/doc/stable/reference/routines.linalg.html" 
style="display: inline-block; 
padding: 10px 20px; 
background-color: #4CAF50; 
color: white; 
text-align: center; 
text-decoration: none; 
border-radius: 5px;">NumPy linag</a>

## Linear Algebra Functions in NumPy
NumPy provides a wide array of functions for linear algebra, ranging from basic matrix operations to more advanced factorizations and decompositions. Below is a categorized list of key linear algebra functions in NumPy:

## Basic Linear Algebra Functions

#### Matrix Multiplication

`np.dot()`

Description: Computes the dot product of two arrays or matrices.

In [14]:
import numpy as np
# Dot product
a = np. array ([[1 , 2], [3, 4]])
b = np. array ([[5 , 6], [7, 8]])
dot_product = np. dot(a, b) # can be done using @ operator
dot_product

array([[19, 22],
       [43, 50]])

`np.matmul()`

Description: Performs matrix multiplication, equivalent to the dot product for 2-D
arrays.

In [3]:
mat_product = np. matmul (a, b)
mat_product

array([[19, 22],
       [43, 50]])

`np.vdot()`

Description: Computes the dot product of two vectors.

In [5]:
vdot_product = np. vdot (a[0] , b [0])
print(vdot_product)

17


`np.cross()` 

The np.cross function in NumPy computes the cross product of two vectors.

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Compute the cross product
cross_product = np.cross(a, b)

print(cross_product)

[-3  6 -3]


### Transpose
`np.transpose()`

Description: Transposes the given array, flipping it over its diagonal.

In [9]:
a = np. array ([[1 , 2], [3, 4]])
print(a)
transposed_a = np.transpose(a)
print(transposed_a)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


`np.swapaxes()`

Description: Swaps two axes of an array.

In [11]:
swapped_axes = np. swapaxes (a, 0, 1)
swapped_axes

array([[1, 3],
       [2, 4]])

### Trace
`np.trace`
Description: Computes the sum of the diagonal elements of a matrix. 

In [13]:
# Trace of an array
trace_a = np.trace(a)
trace_a

np.int64(5)

## Solving Linear Systems
#### Solve Ax = b
`np.linalg.solve(a, b)`

Description: Solves the linear equation Ax = b for x.

Solve the systemm of linear equation:

$$
3x + 2y = 7 \\
x - 3y = -5
$$

In [17]:
a = np.array([[3, 2],
              [1, -3]])
b = np. array ([7 , -5])
x = np.linalg.solve (a, b)
print(x)

[1. 2.]


### Matrix Inversion
`np.linalg.inv(a)`
Description: Computes the inverse of a square matrix.

In [19]:
# Compute the inverse of a matrix
inv_a = np.linalg.inv(a)
inv_a

array([[ 0.27272727,  0.18181818],
       [ 0.09090909, -0.27272727]])

#### Solving using inverse of matrix.

Solve the systemm of linear equation:

$$
2x + y = -1 \\
5x - 3y = -8
$$

In [20]:
a = np.array([[2, 1],
              [5, -3]])
b = np. array ([-1 , -8])
inv_a = np.linalg.inv(a)
x = inv_a @ b
print(x)

[-1.  1.]



2.3 Least-Squares Solution
Description: Computes the least-squares solution to a linear matrix equation.
1 # Least - squares solution
2 x_least_squares , residuals , rank , s = np. linalg . lstsq (a, b, rcond =
None )
3 Decompositions
3.1 Eigenvalue Decomposition
Description: Computes the eigenvalues and right eigenvectors of a square array.
1 # Eigenvalue and eigenvector computation
2 eigenvalues , eigenvectors = np. linalg .eig(a)
3.2 Singular Value Decomposition (SVD)
Description: Factorizes a matrix into three matrices, representing its intrinsic properties.
1 # Singular Value Decomposition
2 u, s, vh = np. linalg .svd (a)
3.3 Cholesky Decomposition
Description: Decomposes a positive-definite matrix into a lower triangular matrix and
its transpose.
1 # Cholesky decomposition
2 L = np. linalg . cholesky (a)
23.4 QR Decomposition
Description: Decomposes a matrix into an orthogonal matrix and an upper triangular
matrix.
1 # QR decomposition
2 q, r = np. linalg .qr(a)
4 Norms and Determinants
4.1 Norms
Description: Computes the norm (length) of a vector or the Frobenius norm of a matrix.
1 # Matrix or vector norm
2 norm_a = np. linalg . norm (a, ord = None )
4.2 Determinant
Description: Computes the determinant of a square matrix.
1 # Compute the determinant of a matrix
2 det_a = np. linalg .det(a)
5 Other Useful Functions
5.1 Matrix Rank
Description: Returns the rank of a matrix, which is the dimension of the vector space
generated by its rows or columns.
1 # Return the rank of a matrix
2 rank_a = np. linalg . matrix_rank (a)
5.2 Condition Number
Description: Computes the condition number of a matrix, indicating how sensitive the
solution of a system of linear equations is to changes in the input.
1 # Compute the condition number of a matrix
2 cond_a = np. linalg . cond (a, p= None )
5.3 Pseudo-Inverse
Description: Computes the Moore-Penrose pseudo-inverse of a matrix.
1 # Compute the Moore - Penrose pseudo - inverse
2 pseudo_inv_a = np. linalg . pinv (a)
35.4 Cross Product
Description: Computes the cross product of two 3-dimensional vectors.
1 # Compute the cross product of two 3D vectors
2 a_vec = np. array ([1 , 2, 3])
3 b_vec = np. array ([4 , 5, 6])
4 cross_product = np. cross (a_vec , b_vec )
6 Utility Functions for Arrays
6.1 Identity Matrix
Description: Returns a 2D array with ones on the diagonal and zeros elsewhere.
1 # Return a 2D array with ones on the diagonal
2 identity_matrix = np.eye (3)
6.2 Diagonal
Description: Extracts or constructs a diagonal array.
1 # Extract or construct a diagonal array
2 diagonal_array = np. diag ([1 , 2, 3])
6.3 Flattening
Description: Returns a contiguous flattened array.
1 # Return a flattened array
2 flattened_a = np. ravel (a)
7 Advanced Linear Algebra Functions
7.1 Kronecker Product
Description: Computes the Kronecker product of two arrays.
1 # Compute the Kronecker product of two arrays
2 kron_product = np. kron (a, b)
7.2 Tensor Dot Product
Description: Computes the tensor dot product along specified axes.
1 # Compute the tensor dot product along specified axes
2 tensor_dot = np. tensordot (a, b, axes =1)
47.3 Element-wise Multiplication
Description: Performs element-wise multiplication of two arrays.
1 # Element - wise multiplication
2 hadamard_product = np. multiply (a, b)
7.4 Matrix Power
Description: Raises a square matrix to an integer power n.
1 # Raise a square matrix to the integer power n
2 matrix_power = np. linalg . matrix_power (a, 2)
8 Higher-Dimensional Tensors
8.1 Mode Product of a Tensor
Description: Computes the mode product of tensors.
1 # Example of using einsum for tensor operations
2 tensor_product = np. einsum (’ij ,jk ->ik ’, a, b)
9 Special Matrix Functions
9.1 Hermitian Matrix Check
Description: Checks if a matrix is Hermitian or symmetric.
1 # Check if a matrix is Hermitian or symmetric
2 is_hermitian = np. iscomplexobj (a)
5