![Python for Physicist](https://github.com/scnilkunwar/Python-for-Physicist/blob/main/images/Banner.png?raw=true)

<div align="center">
    
![Numpy](https://raw.githubusercontent.com/numpy/numpy/main/branding/logo/primary/numpylogo.svg)
  <h1> Python for Physicist - NumPy Linear Algebra</h1>
</div>

<a href="https://numpy.org/doc/stable/reference/routines.linalg.html" 
style="display: inline-block; 
padding: 10px 20px; 
background-color: #4CAF50; 
color: white; 
text-align: center; 
text-decoration: none; 
border-radius: 5px;">NumPy linalg</a>

## Linear Algebra Functions in NumPy
NumPy provides a wide array of functions for linear algebra, ranging from basic matrix operations to more advanced factorizations and decompositions. Below is a categorized list of key linear algebra functions in NumPy:

## Basic Linear Algebra Functions

#### Matrix Multiplication

`np.dot()`

Description: Computes the dot product of two arrays or matrices.

In [1]:
import numpy as np
# Dot product
a = np. array ([[1 , 2], [3, 4]])
b = np. array ([[5 , 6], [7, 8]])
dot_product = np. dot(a, b) # can be done using @ operator
dot_product

array([[19, 22],
       [43, 50]])

`np.matmul()`

Description: Performs matrix multiplication, equivalent to the dot product for 2-D
arrays.

In [2]:
mat_product = np. matmul (a, b)
mat_product

array([[19, 22],
       [43, 50]])

`np.vdot()`

Description: Computes the dot product of two vectors.

In [3]:
vdot_product = np. vdot (a[0] , b [0])
print(vdot_product)

17


`np.cross()` 

The np.cross function in NumPy computes the cross product of two vectors.

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Compute the cross product
cross_product = np.cross(a, b)

print(cross_product)

[-3  6 -3]


### Transpose
`np.transpose()`

Description: Transposes the given array, flipping it over its diagonal.

In [5]:
a = np. array ([[1 , 2], [3, 4]])
print(a)
transposed_a = np.transpose(a) #a.T
print(transposed_a)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


`np.swapaxes()`

Description: Swaps two axes of an array.

In [6]:
swapped_axes = np.swapaxes (a, 0, 1)
swapped_axes

array([[1, 3],
       [2, 4]])

### Trace
`np.trace`
Description: Computes the sum of the diagonal elements of a matrix. 

In [7]:
# Trace of an array
trace_a = np.trace(a)
trace_a

np.int64(5)

## Solving Linear Systems
#### Solve Ax = b
`np.linalg.solve(a, b)`

Description: Solves the linear equation Ax = b for x.

Solve the systemm of linear equation:

$$
3x + 2y = 7 \\
x - 3y = -5
$$

In [8]:
a = np.array([[3, 2],
              [1, -3]])
b = np. array ([7 , -5])
x = np.linalg.solve (a, b)
print(x)

[1. 2.]


### Matrix Inversion
`np.linalg.inv(a)`
Description: Computes the inverse of a square matrix.

In [9]:
# Compute the inverse of a matrix
inv_a = np.linalg.inv(a)
inv_a

array([[ 0.27272727,  0.18181818],
       [ 0.09090909, -0.27272727]])

#### Solving using inverse of matrix.

Solve the systemm of linear equation:

$$
2x + y = -1 \\
5x - 3y = -8
$$

In [10]:
a = np.array([[2, 1],
              [5, -3]])
b = np. array ([-1 , -8])
inv_a = np.linalg.inv(a)
x = inv_a @ b
print(x)
print(np.linalg.solve(a, b))

[-1.  1.]
[-1.  1.]


In [11]:
print(np.linalg.lstsq(a, b))

(array([-1.,  1.]), array([], dtype=float64), np.int32(2), array([5.96667765, 1.84357203]))


## Decompositions
## Eigenvalue Decomposition
`np.linalg.eig(a)`

Description: Computes the eigenvalues and right eigenvectors of a square array.

In [12]:
# Eigenvalue and eigenvector computation
eigenvalues , eigenvectors = np. linalg .eig(a)
print(eigenvalues)
print(eigenvectors) #each column

[ 2.85410197 -3.85410197]
[[ 0.76039797 -0.16838141]
 [ 0.6494574   0.98572192]]


In [13]:
print(a)

[[ 2  1]
 [ 5 -3]]


In [14]:
print(a @ eigenvectors[:, 1])

[ 0.64895911 -3.79907279]


In [15]:
print(eigenvalues[1] * eigenvectors[:, 1])

[ 0.64895911 -3.79907279]


### Singular Value Decomposition (SVD)
`np.linalg.svd()`

Description: Factorizes a matrix into three matrices, representing its intrinsic properties.

### Singular Value Decomposition (SVD)

**Singular Value Decomposition (SVD)** is a fundamental concept in linear algebra, particularly useful in various applications such as signal processing, statistics, and machine learning. It decomposes a matrix into three other matrices, revealing important properties of the original matrix.

### Definition

For any $( m \times n )$ matrix $ A$, SVD states that you can decompose $ A $ into the following form:

$$
A = U \Sigma V^T
$$

where:
- $ U $ is an $( m \times m )$ orthogonal matrix whose columns are the left singular vectors of \( A \).
- $( \Sigma )$ is an $( m \times n )$ diagonal matrix with non-negative real numbers on the diagonal, known as the singular values of $ A $.
- $( V^T )$ is the transpose of an $( n \times n )$ orthogonal matrix $ V $, whose columns are the right singular vectors of $ A $.

### Properties
1. **Orthogonality**: The columns of \( U \) and \( V \) are orthonormal.
   - $( U^T U = I )$
   - $( V^T V = I )$
2. **Singular Values**: The singular values in $ \Sigma 0$ are sorted in descending order:
   $$
   \sigma_1 \geq \sigma_2 \geq \cdots \geq \sigma_r \geq 0
   $$
   where \( r \) is the rank of the matrix \( A \).
3. **Reconstruction**: The original matrix \( A \) can be reconstructed from \( U \), $( \Sigma )$, and $( V^T )$.

### Applications
- **Dimensionality Reduction**: SVD is widely used in Principal Component Analysis (PCA) for reducing the number of features in data.
- **Image Compression**: It helps in approximating images with fewer components, thereby reducing storage requirements.
- **Recommender Systems**: SVD is utilized in collaborative filtering for recommending items to users.

In [16]:
# Singular Value Decomposition
u, s, vh = np.linalg.svd(a)
u, s, vh

(array([[-0.2229892 , -0.97482092],
        [-0.97482092,  0.2229892 ]]),
 array([5.96667765, 1.84357203]),
 array([[-0.89163238,  0.4527601 ],
        [-0.4527601 , -0.89163238]]))

### Cholesky Decomposition
`np.linalg.cholesky(a)`
Description: Decomposes a positive-definite matrix into a lower triangular matrix and
its transpose.

### Cholesky Decomposition

**Cholesky decomposition** is a method of decomposing a symmetric, positive-definite matrix into the product of a lower triangular matrix and its transpose. It is commonly used in numerical analysis, particularly for solving systems of linear equations and performing matrix inversion.

### Definition

For a symmetric positive-definite matrix $ A $, the Cholesky decomposition states:

$$
A = L L^T
$$

where:
- $ A $ is the original matrix.
- $ L $ is a lower triangular matrix.
- $ L^T $ is the transpose of $ L $.

### Properties
1. **Symmetric**: The original matrix $ A $ must be symmetric, meaning $ A = A^T $.
2. **Positive-Definite**: The matrix must be positive-definite, which generally implies that all its leading principal minors are positive.
3. **Unique**: The decomposition is unique for symmetric positive-definite matrices.

In [17]:
# Define a symmetric positive-definite matrix
A = np.array([[4, 2],
              [2, 3]])

# Perform Cholesky decomposition
L = np.linalg.cholesky(A)

# Display the results
print("Original Matrix A:")
print(A)
print("\nLower Triangular Matrix L:")
print(L)

# Verify that A = L @ L^T
A_reconstructed = L @ L.T
print("\nReconstructed Matrix A from L:")
print(A_reconstructed)

Original Matrix A:
[[4 2]
 [2 3]]

Lower Triangular Matrix L:
[[2.         0.        ]
 [1.         1.41421356]]

Reconstructed Matrix A from L:
[[4. 2.]
 [2. 3.]]


### QR Decomposition
`np.linalg.qr(a)`

Description: Decomposes a matrix into an orthogonal matrix and an upper triangular
matrix.

### QR Decomposition

**QR decomposition** is a method of decomposing a matrix into a product of an orthogonal matrix and an upper triangular matrix. This decomposition is widely used in numerical linear algebra, particularly for solving linear systems, least squares problems, and eigenvalue computations.

### Definition

For a given matrix $ A $ of size $ m \times n $, the QR decomposition states:

$$
A = Q R
$$

where:
- $ A $ is the original matrix.
- $ Q $ is an orthogonal matrix (or orthonormal if its columns are normalized).
- $ R $ is an upper triangular matrix.

### Properties
1. **Orthogonality**: The columns of the matrix $ Q $ are orthogonal (i.e., $ Q^T Q = I $), where $ I $ is the identity matrix.
2. **Upper Triangular**: The matrix $ R $ is upper triangular, meaning all entries below the main diagonal are zero.
3. **Unique**: The QR decomposition is unique when the columns of $ A $ are linearly independent.

In [18]:
# Define a matrix A
A = np.array([[12, -51, 4],
              [6, 167, -68],
              [-4, 24, -41]])

# Perform QR decomposition
Q, R = np.linalg.qr(A)

# Display the results
print("Original Matrix A:")
print(A)
print("\nOrthogonal Matrix Q:")
print(Q)
print("\nUpper Triangular Matrix R:")
print(R)

# Verify that A = Q @ R
A_reconstructed = Q @ R
print("\nReconstructed Matrix A from Q and R:")
print(A_reconstructed)

Original Matrix A:
[[ 12 -51   4]
 [  6 167 -68]
 [ -4  24 -41]]

Orthogonal Matrix Q:
[[-0.85714286  0.39428571  0.33142857]
 [-0.42857143 -0.90285714 -0.03428571]
 [ 0.28571429 -0.17142857  0.94285714]]

Upper Triangular Matrix R:
[[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]

Reconstructed Matrix A from Q and R:
[[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -41.]]


## Norms and Determinants
### Norms
`np.linalg.norm(a, ord = None )`

Description: Computes the norm (length) of a vector or the Frobenius norm of a matrix.

### Norm of a Vector

The **norm** of a vector is a measure of its length or magnitude. It provides a way to quantify the size of a vector in a vector space.

1. **Euclidean Norm** ($L^2$ Norm):
   The Euclidean norm of a vector $ \mathbf{v} \in \mathbb{R}^n $ is defined as:

   $$
   \|\mathbf{v}\|_2 = \sqrt{\sum_{i=1}^{n} v_i^2}
   $$

   where $ v_i $ are the components of the vector $ \mathbf{v} $.

In [19]:
# Define a vector
v = np.array([3, 4])

euclidean_norm = np.linalg.norm(v)


# Display the results
print("Vector v:")
print(v)
print("\nEuclidean Norm (L2):", euclidean_norm)


Vector v:
[3 4]

Euclidean Norm (L2): 5.0


### Norm of a Matrix

The **norm** of a matrix is a measure of the size or magnitude of the matrix. Similar to vector norms, matrix norms provide insights into the behavior of linear transformations represented by matrices.

1. **Frobenius Norm** ($\|\cdot\|_F$):
   The Frobenius norm of a matrix $ A \in \mathbb{R}^{m \times n} $ is defined as:

   $$
   \|A\|_F = \sqrt{\sum_{i=1}^{m} \sum_{j=1}^{n} |a_{ij}|^2}
   $$

   where $ a_{ij} $ are the elements of the matrix $ A $.

In [20]:
# Define a matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Calculate Frobenius norm
frobenius_norm = np.linalg.norm(A)

# Calculate Infinity norm
infinity_norm = np.linalg.norm(A, np.inf)

# Calculate 1-norm
one_norm = np.linalg.norm(A, 1)

# Display the results
print("Matrix A:")
print(A)
print("\nFrobenius Norm:", frobenius_norm)
print("Infinity Norm:", infinity_norm)
print("1-Norm:", one_norm)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Frobenius Norm: 16.881943016134134
Infinity Norm: 24.0
1-Norm: 18.0


### Determinant
`np.linalg.det(a)`

Description: Computes the determinant of a square matrix.

In [21]:
# Define a matrix A
A = np.array([[1, 2, 3],
              [4, 6, 6],
              [7, 8, 9]])
det_a = np.linalg.det(A)
print(det_a)

-12.0


### Matrix Rank
`np.linalg.matrix_rank(a)`

Description: Returns the rank of a matrix, which is the dimension of the vector space
generated by its rows or columns.

### Rank of a Matrix

The **rank** of a matrix is a fundamental concept in linear algebra that provides important information about the matrix's properties. Specifically, the rank indicates the maximum number of linearly independent row or column vectors in the matrix. It helps determine the dimensions of the row space and column space of the matrix.

### Definition

For a matrix $ A \in \mathbb{R}^{m \times n} $, the rank is defined as:

$$
\text{rank}(A) = \text{dim}(\text{Row space of } A) = \text{dim}(\text{Column space of } A)
$$

where:
- $\text{dim}(\cdot)$ denotes the dimension of a vector space.
- The row space consists of all linear combinations of the row vectors of $ A $.
- The column space consists of all linear combinations of the column vectors of $ A $.

### Properties
1. **Rank Range**: The rank of a matrix $ A $ satisfies the inequality:
   $$
   0 \leq \text{rank}(A) \leq \min(m, n)
   $$
   where $ m $ is the number of rows and $ n $ is the number of columns.

2. **Full Rank**: A matrix is said to have full rank if $\text{rank}(A) = \min(m, n)$.

3. **Linear Dependence**: If the rank of a matrix is less than its number of rows or columns, it indicates that there are linearly dependent vectors.

In [22]:
# Define a matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Calculate the rank of the matrix
rank_A = np.linalg.matrix_rank(A)

# Display the result
print("Matrix A:")
print(A)
print("\nRank of Matrix A:", rank_A)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Rank of Matrix A: 2


In [23]:
# Define a matrix A
A = np.array([[1, 2, 3],
              [4, 6, 6],
              [7, 8, 9]])
rank = np.linalg.matrix_rank(A)
print(rank)

3


### Pseudo-Inverse of a Matrix

The **pseudo-inverse** of a matrix is a generalization of the matrix inverse that can be applied to non-square or singular matrices. The pseudo-inverse is particularly useful in solving linear equations, especially in least squares problems.

### Definition

For a matrix $ A \in \mathbb{R}^{m \times n} $, the pseudo-inverse, denoted as $ A^+ $, can be defined using the Singular Value Decomposition (SVD) or by using the Moore-Penrose conditions. The pseudo-inverse satisfies the following conditions:

1. $ AA^+A = A $
2. $ A^+AA^+ = A^+ $
3. $ (AA^+)^T = AA^+ $
4. $ (A^+A)^T = A^+A $

The pseudo-inverse is computed as:

$$
A^+ = V \Sigma^+ U^T
$$

where $ A = U \Sigma V^T $ is the SVD of $ A $, and $ \Sigma^+ $ is obtained by taking the reciprocal of the non-zero singular values in $ \Sigma $ and transposing the resulting matrix.

### Pseudo-Inverse in NumPy

You can calculate the pseudo-inverse of a matrix using NumPy with the `numpy.linalg.pinv` function. Here's how to use it:

In [24]:
# Define a matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Calculate the pseudo-inverse of the matrix
pseudo_inverse_A = np.linalg.pinv(A)

# Display the results
print("Matrix A:")
print(A)
print("\nPseudo-Inverse of Matrix A:")
print(pseudo_inverse_A)

# Verify the properties of the pseudo-inverse
print("\nVerify AA^+A = A:")
print(np.dot(A, np.dot(pseudo_inverse_A, A)))

print("\nVerify A^+AA^+ = A^+:")
print(np.dot(pseudo_inverse_A, np.dot(A, pseudo_inverse_A)))

Matrix A:
[[1 2 3]
 [4 5 6]]

Pseudo-Inverse of Matrix A:
[[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]

Verify AA^+A = A:
[[1. 2. 3.]
 [4. 5. 6.]]

Verify A^+AA^+ = A^+:
[[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]


### Cross Product
`np.cross()`

Description: Computes the cross product of two 3-dimensional vectors.

In [25]:
# Compute the cross product of two 3D vectors
a_vec = np. array ([1 , 2, 3])
b_vec = np. array ([4 , 5, 6])
cross_product = np. cross (a_vec , b_vec )
cross_product

array([-3,  6, -3])

### Kronecker Product

The **Kronecker product** is a mathematical operation on two matrices that produces a block matrix. It is denoted by the symbol $\otimes$. The Kronecker product is used in various fields such as mathematics, engineering, and physics, especially in systems involving tensor products.

### Definition

For two matrices $A \in \mathbb{R}^{m \times n}$ and $B \in \mathbb{R}^{p \times q}$, the Kronecker product $A \otimes B$ results in a matrix of size $(m \cdot p) \times (n \cdot q)$. The entries of the Kronecker product are computed as follows:

$$
A \otimes B = 
\begin{bmatrix}
a_{11}B & a_{12}B & \cdots & a_{1n}B \\
a_{21}B & a_{22}B & \cdots & a_{2n}B \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1}B & a_{m2}B & \cdots & a_{mn}B
\end{bmatrix}
$$

where $a_{ij}$ are the elements of matrix $A$.

### Properties

1. **Dimensions**: If $A$ is $m \times n$ and $B$ is $p \times q$, then $A \otimes B$ is $(m \cdot p) \times (n \cdot q)$.

2. **Associativity**: The Kronecker product is associative, meaning $(A \otimes B) \otimes C = A \otimes (B \otimes C)$.

3. **Distributivity**: The Kronecker product is distributive over matrix addition:
   $$
   A \otimes (B + C) = (A \otimes B) + (A \otimes C)
   $$

4. **Identity Matrix**: The Kronecker product with an identity matrix behaves similarly to scalar multiplication:
   $$
   A \otimes I_n = A \text{ (where } I_n \text{ is the } n \times n \text{ identity matrix)}
   $$

### Applications
- **Quantum Mechanics**: Used in representing multi-particle systems.
- **Signal Processing**: Helps in the analysis of signals with multiple channels.
- **Statistics**: Useful in multivariate statistics and regression analysis.
- **Computer Graphics**: Employed in transformations and rendering techniques.
### Kronecker Product in NumPy

You can compute the Kronecker product in Python using NumPy with the `numpy.kron` function. Here’s how to do it:

In [26]:
# Define matrices A and B
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[0, 5],
              [6, 7]])

# Calculate the Kronecker product
kron_product = np.kron(A, B)

# Display the results
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nKronecker Product A ⊗ B:")
print(kron_product)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[0 5]
 [6 7]]

Kronecker Product A ⊗ B:
[[ 0  5  0 10]
 [ 6  7 12 14]
 [ 0 15  0 20]
 [18 21 24 28]]


### Tensor Dot Product

The **tensor dot product** is a generalization of the dot product that can be applied to tensors of any rank (dimension). It combines two tensors and contracts over specified axes, resulting in a new tensor. This operation is commonly used in fields such as physics, engineering, and machine learning.

### Definition

Given two tensors $A$ and $B$, the tensor dot product is defined as:

$$
C = A \odot B
$$

Where $C$ is the resulting tensor after performing the dot product.

### Mathematical Representation

For tensors $A$ and $B$, the tensor dot product is computed by summing the products of their elements over the specified axes. If $A$ is of shape $(i_1, i_2, \ldots, i_m)$ and $B$ is of shape $(j_1, j_2, \ldots, j_n)$, the tensor dot product will produce a tensor with dimensions determined by the axes specified for contraction.

### Example

For instance, if we have:

- Tensor $A$ with shape $(2, 3)$
- Tensor $B$ with shape $(3, 4)$

The tensor dot product can be computed over the second axis of $A$ and the first axis of $B$, resulting in a tensor $C$ of shape $(2, 4)$.

### Properties

1. **Associativity**: The tensor dot product is associative:
   $$
   A \odot (B \odot C) = (A \odot B) \odot C
   $$

2. **Distributivity**: The tensor dot product is distributive over addition:
   $$
   A \odot (B + C) = A \odot B + A \odot C
   $$

3. **Commutativity**: In general, the tensor dot product is not commutative:
   $$
   A \odot B \neq B \odot A
   $$

4. **Linearity**: The tensor dot product is linear in each of its arguments. That is, for scalars $\alpha$ and $\beta$:
   $$
   \alpha (A \odot B) + \beta (A \odot C) = A \odot (\alpha B + \beta C)
   $$

5. **Inner Product**: For vector spaces, if both tensors are vectors (1D tensors), then the tensor dot product corresponds to the standard inner product.

### Applications

- **Physics**: Used in calculations involving vector and tensor fields, such as in continuum mechanics and relativity.

- **Machine Learning**: Useful in neural networks, particularly in operations involving tensors for deep learning, where inputs and weights are often represented as multi-dimensional arrays.

- **Computer Graphics**: Applied in transformations and rendering algorithms involving multi-dimensional data, especially in 3D graphics and simulations.

- **Signal Processing**: Used in multi-channel signal processing, where signals are represented as tensors and various operations are performed.

- **Quantum Computing**: In quantum mechanics, the states of systems are often represented as tensors, and tensor dot products are used in operations involving quantum states.

### Tensor Dot Product in NumPy

In Python, you can compute the tensor dot product using the `numpy.tensordot` function. Here’s how to do it:

In [27]:
# Define tensors A and B
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# Calculate the tensor dot product
tensor_dot_product = np.tensordot(A, B, axes=1)

# Display the results
print("Tensor A:")
print(A)
print("\nTensor B:")
print(B)
print("\nTensor Dot Product A • B:")
print(tensor_dot_product)

Tensor A:
[[1 2 3]
 [4 5 6]]

Tensor B:
[[ 7  8]
 [ 9 10]
 [11 12]]

Tensor Dot Product A • B:
[[ 58  64]
 [139 154]]
