![Python for Physicist](https://github.com/scnilkunwar/Python-for-Physicist/blob/main/images/Banner.png?raw=true)

<div align="center">
    
![Numpy](https://raw.githubusercontent.com/numpy/numpy/main/branding/logo/primary/numpylogo.svg)
  <h1> Python for Physicist - NumPy Statistics</h1>
</div>

<a href="https://numpy.org/devdocs/reference/routines.statistics.html" 
style="display: inline-block; 
padding: 10px 20px; 
background-color: #4CAF50; 
color: white; 
text-align: center; 
text-decoration: none; 
border-radius: 5px;">NumPy Statistics</a>

# Statistics in Arrays

## Order Statistics

- **`ptp(a, axis, out, keepdims)`**  
  Range of values (maximum - minimum) along an axis.

In [1]:
from numpy import *
from numpy.random import *

In [2]:
ptp(array([1, 3, 2, 6, 8, 9, 1]))

np.int64(8)

In [3]:
A = randint(0, 20, (3, 4))
A

array([[ 6,  8, 11,  0],
       [ 2, 11, 15, 19],
       [ 0,  1,  0,  9]], dtype=int32)

In [4]:
ptp(A, axis=1)

array([11, 17,  9], dtype=int32)

- **`percentile(a, q, axis, out, ...)`**  
  Compute the q-th percentile of the data along the specified axis.

In [5]:
a = randint(1, 5000, 101)
a.sort()
a

array([   4,   74,  127,  159,  160,  196,  200,  281,  329,  393,  412,
        429,  436,  438,  442,  532,  539,  562,  583,  588,  618,  621,
        627,  812,  849,  930,  952,  956, 1001, 1005, 1038, 1189, 1215,
       1477, 1612, 1614, 1620, 1639, 1729, 1733, 1920, 1948, 1986, 2058,
       2075, 2087, 2126, 2150, 2176, 2178, 2278, 2378, 2407, 2408, 2476,
       2496, 2507, 2577, 2624, 2635, 2681, 2695, 2781, 2865, 2865, 2926,
       2930, 3015, 3032, 3059, 3089, 3094, 3162, 3286, 3300, 3342, 3403,
       3419, 3513, 3518, 3531, 3545, 3561, 3603, 3709, 3928, 4148, 4182,
       4373, 4378, 4380, 4402, 4453, 4467, 4497, 4560, 4755, 4769, 4789,
       4852, 4981], dtype=int32)

In [6]:
percentile(a, 25)

np.float64(930.0)

- **`nanpercentile(a, q, axis, out, ...)`**  
  Compute the q-th percentile of the data along the specified axis, while ignoring NaN values.

- **`quantile(a, q, axis, out, overwrite_input, ...)`**  
  Compute the q-th quantile of the data along the specified axis.

In [7]:
quantile(a, 0.25)

np.float64(930.0)


- **`nanquantile(a, q, axis, out, ...)`**  
  Compute the q-th quantile of the data along the specified axis, while ignoring NaN values.

## Averages and Variances

- **`median(a, axis, out, overwrite_input, keepdims)`**  
  Compute the median along the specified axis.

- **`average(a, axis, weights, returned, keepdims)`**  
  Compute the weighted average along the specified axis.

- **`mean(a, axis, dtype, out, keepdims, where)`**  
  Compute the arithmetic mean along the specified axis.

- **`std(a, axis, dtype, out, ddof, keepdims, ...])`**  
  Compute the standard deviation along the specified axis.

- **`var(a, axis, dtype, out, ddof, keepdims, ...)`**  
  Compute the variance along the specified axis.

- **`nanmedian(a, axis, out, overwrite_input, ...)`**  
  Compute the median along the specified axis, while ignoring NaNs.

- **`nanmean(a, axis, dtype, out, keepdims, where])`**  
  Compute the arithmetic mean along the specified axis, ignoring NaNs.

- **`nanstd(a, axis, dtype, out, ddof, ...)`**  
  Compute the standard deviation along the specified axis, while ignoring NaNs.

- **`nanvar(a, axis, dtype, out, ddof, ...)`**  
  Compute the variance along the specified axis, while ignoring NaNs.

## Correlating

- **`corrcoef(x, y, rowvar, bias, ddof, dtype)`**  
  Return Pearson product-moment correlation coefficients.

- **`correlate(a, v, mode)`**  
  Cross-correlation of two 1-dimensional sequences.

- **`cov(m, y, rowvar, bias, ddof, fweights, ...)`**  
  Estimate a covariance matrix, given data and weights.

In [9]:
x = randint(1, 50, 10)
y = randint(1, 50, 10)
corr_coeff = corrcoef(x, y)
corr_coeff

array([[ 1.        , -0.03734199],
       [-0.03734199,  1.        ]])

## Histograms

- **`histogram(a[, bins, range, density, weights])`**  
  Compute the histogram of a dataset.

- **`histogram2d(x, y[, bins, range, density, ...])`**  
  Compute the bi-dimensional histogram of two data samples.

- **`histogramdd(sample[, bins, range, density, ...])`**  
  Compute the multidimensional histogram of some data.

- **`bincount(x, /[, weights, minlength])`**  
  Count number of occurrences of each value in an array of non-negative integers.

- **`histogram_bin_edges(a[, bins, range, weights])`**  
  Function to calculate only the edges of the bins used by the histogram function.

- **`digitize(x, bins[, right])`**  
  Return the indices of the bins to which each value in the input array belongs.

## Additional Statistical Functions

- **`trapz(y, x=None, dx=1.0, axis=-1)`**  
  Integrate along the specified axis using the trapezoidal rule.

- **`cumsum(a, axis=None, dtype=None, out=None)`**  
  Return the cumulative sum of the elements along a given axis.

- **`cumprod(a, axis=None, dtype=None, out=None)`**  
  Return the cumulative product of the elements along a given axis.

- **`diff(a, n=1, axis=-1, prepend=0, append=0)`**  
  Calculate the n-th discrete difference along the given axis.

- **`ediff1d(ary, to_end=None, to_begin=None)`**  
  Calculate the differences between consecutive elements of an array.

- **`gradient(f, *varargs, axis=None, edge_order=1)`**  
  Return the gradient of an N-dimensional array.

- **`median_absolute_deviation(a, axis=0, center=np.median, scale=1.0)`**  
  Compute the median absolute deviation of the data along the specified axis.

- **`mode(a, axis=0, nan_policy='propagate')`**  
  Return the mode(s) of the array, the most frequent value in the dataset.

- **`skew(a, axis=0, bias=True, nan_policy='propagate')`**  
  Compute the skewness of data along the specified axis.

- **`kurtosis(a, axis=0, fisher=True, bias=True, nan_policy='propagate')`**  
  Compute the kurtosis (degree of tailedness) of the data along the specified axis.
